### PR TITLE
Add A11y for auditing accessibility [PLAT-7883]

### PR DESCRIPTION
**Pull request by mudnug**

### CODE REVIEW

**Comment by mudnug** [comment]
@billpull, @chriskrycho, @gshackles ... would one of you like to review and merge this?

**Comment by gshackles** [comment]
Can we just make these changes right inside our site Gulpfile(s) for now instead of pushing it into this package? We can abstract things into here down the line as needed.

**Comment by mudnug** [comment]
Sure, that's not a problem. I thought doing so would be rejected, though. I haven't seen that done before

**Comment by gshackles** [comment]
Yeah that's fine for stuff like this, especially while we prove out what's actually needed. This is mostly just here to make it easy for projects to access commonly used things, but there's no reason projects can't layer in things of their own too

**Pull request closed without merging**
