### PR TITLE
Update olo-gulp-helpers to fix deprecations and vulnerabilities. [PLAT-14798]

### PR DESCRIPTION
**Pull request by chriskrycho**
JIRA Issue: [PLAT-14798](https://ololabs.atlassian.net/browse/PLAT-14798)

Note that this is strictly speaking a breaking change. However, I've tested it in all of our apps which consume these dependencies, and things are working as expected throughout. (I have not yet bumped the version (to 0.4.0) because my own preference is to do that simultaneous with publication to prevent `package.json` and tagged/released versions from ever being out of sync.)

Given our supported Node versions all support modern ES features, I also modernized these implementations to match our current coding standards.

### CODE REVIEW

**Review by billpull — APPROVED** [review]
@chriskrycho should this also bump the version of this package?

**Comment by chriskrycho** [comment]
@billpull I always wait to bump version until I am actually ready to publish. I've gotten (and had package mangers get) confused by that on personal projects before. I'm good with doing whatever our normal is, though.

**Comment by billpull** [comment]
@chriskrycho makes sense

**Comment by billpull** [comment]
Was able to install via local FS and run Ghost bundle commands

**Pull request merged**
